import json
import os

TRANSLATIONS = {
    "en_us": {
        "helpbox.ui.sacks.first_time_title": "No Sack Data Cached Yet",
        "helpbox.ui.sacks.first_time_desc": "Please close and re-open the Sacks screen once to populate data.",
        "helpbox.ui.sacks.btn_fetch": "🔄 Fetch Sack Data",
        "helpbox.ui.tab.storage": "HelpBox Vault",
        "helpbox.ui.storage.title": "HelpBox Vault",
        "helpbox.ui.storage.subtitle": "Unified overlays for Ender Chests, Backpacks & Rift",
        "helpbox.ui.vault.title": "HelpBox Vault",
        "helpbox.ui.vault.settings": "Vault Settings",
        "helpbox.ui.vault.settings_btn": "✦ Open Vault Settings",
        "helpbox.ui.vault.settings_title": "✦ HelpBox Vault Settings",
        "helpbox.ui.vault.theme": "Appearance Theme:",
        "helpbox.ui.vault.pages_per_row": "Cards per Row:",
        "helpbox.ui.vault.card_spacing": "Card Spacing (px):",
        "helpbox.ui.vault.auto_scroll": "Auto-Scroll:",
        "helpbox.ui.vault.scroll_off": "Off",
        "helpbox.ui.vault.scroll_partly": "Partial",
        "helpbox.ui.vault.scroll_fully": "Full",
        "helpbox.ui.vault.enable_vault": "Enable Vault Overlay",
        "helpbox.ui.vault.enable_rift": "Enable Rift Vault",
        "helpbox.ui.vault.save_close": "Save & Close",
        "helpbox.ui.tab.sacks": "HelpBox Sacks",
        "helpbox.ui.sacks.title": "HelpBox Sacks",
        "helpbox.ui.sacks.subtitle": "Hypixel SkyBlock sack management and quick access overlay",
        "helpbox.ui.buttons.rp_on": "🎨 Resource Pack: ON",
        "helpbox.ui.buttons.rp_off": "🎨 Resource Pack: OFF",
        "helpbox.ui.picker.title": "✦ Icon & Block Picker",
        "helpbox.ui.picker.search_hint": "Search icons or items...",
        "helpbox.ui.picker.choose": "Pick Icon",
        "helpbox.ui.picker.open_hint": "Click to open Icon Picker",
        "helpbox.ui.picker.selected": "✓ Selected icon: %s",
        "helpbox.ui.picker.rp_on": "🎨 Resource Pack: ON",
        "helpbox.ui.picker.rp_off": "🎨 Resource Pack: OFF"
    },
    "tr_tr": {
        "helpbox.ui.sacks.first_time_title": "Henüz Sacks Verisi Bulunamadı",
        "helpbox.ui.sacks.first_time_desc": "Verilerin yüklenmesi için ekranı bir kez kapatıp tekrar açınız.",
        "helpbox.ui.sacks.btn_fetch": "🔄 Sacks Verilerini Getir",
        "helpbox.ui.tab.storage": "HelpBox Kasa & Depo",
        "helpbox.ui.storage.title": "HelpBox Kasa & Depo",
        "helpbox.ui.storage.subtitle": "Ender Sandığı, Sırt Çantaları ve Rift için modern kasa arayüzü",
        "helpbox.ui.vault.title": "HelpBox Kasa",
        "helpbox.ui.vault.settings": "Kasa Ayarları",
        "helpbox.ui.vault.settings_btn": "✦ Kasa Ayarlarını Aç",
        "helpbox.ui.vault.settings_title": "✦ HelpBox Kasa Ayarları",
        "helpbox.ui.vault.theme": "Görünüm Teması:",
        "helpbox.ui.vault.pages_per_row": "Satır Başına Sayfa:",
        "helpbox.ui.vault.card_spacing": "Kart Aralığı (px):",
        "helpbox.ui.vault.auto_scroll": "Oto Kaydırma:",
        "helpbox.ui.vault.scroll_off": "Kapalı",
        "helpbox.ui.vault.scroll_partly": "Kısmi",
        "helpbox.ui.vault.scroll_fully": "Tam",
        "helpbox.ui.vault.enable_vault": "Kasa Arayüzünü Etkinleştir",
        "helpbox.ui.vault.enable_rift": "Rift Kasasını Etkinleştir",
        "helpbox.ui.vault.save_close": "Kaydet & Kapat",
        "helpbox.ui.tab.sacks": "Sacks",
        "helpbox.ui.sacks.title": "Sacks",
        "helpbox.ui.sacks.subtitle": "Hypixel SkyBlock çuval yönetimi ve hızlı erişim arayüzü",
        "helpbox.ui.buttons.rp_on": "🎨 Kaynak Paketi: AÇIK",
        "helpbox.ui.buttons.rp_off": "🎨 Kaynak Paketi: KAPALI",
        "helpbox.ui.picker.title": "✦ İkon & Blok Seçici",
        "helpbox.ui.picker.search_hint": "İkon veya eşya ara...",
        "helpbox.ui.picker.choose": "İkon Seç",
        "helpbox.ui.picker.open_hint": "İkon seçiciyi açmak için tıklayın",
        "helpbox.ui.picker.selected": "✓ İkon seçildi: %s",
        "helpbox.ui.picker.rp_on": "🎨 Kaynak Paketi: AÇIK",
        "helpbox.ui.picker.rp_off": "🎨 Kaynak Paketi: KAPALI"
    },
    "de_de": {
        "helpbox.ui.sacks.first_time_title": "Noch keine Sack-Daten im Cache",
        "helpbox.ui.sacks.first_time_desc": "Bitte schließen und öffnen Sie das Fenster einmal, um Daten zu laden.",
        "helpbox.ui.sacks.btn_fetch": "🔄 Sack-Daten laden",
        "helpbox.ui.tab.storage": "HelpBox Tresor",
        "helpbox.ui.storage.title": "HelpBox Tresor",
        "helpbox.ui.storage.subtitle": "Einheitliche Overlays für Endertruhe, Rucksäcke & Rift",
        "helpbox.ui.vault.title": "HelpBox Tresor",
        "helpbox.ui.vault.settings": "Tresor-Einstellungen",
        "helpbox.ui.vault.settings_btn": "✦ Tresor-Einstellungen öffnen",
        "helpbox.ui.vault.settings_title": "✦ HelpBox Tresor-Einstellungen",
        "helpbox.ui.vault.theme": "Design-Thema:",
        "helpbox.ui.vault.pages_per_row": "Karten pro Zeile:",
        "helpbox.ui.vault.card_spacing": "Kartenabstand (px):",
        "helpbox.ui.vault.auto_scroll": "Autom. Scrollen:",
        "helpbox.ui.vault.scroll_off": "Aus",
        "helpbox.ui.vault.scroll_partly": "Teilweise",
        "helpbox.ui.vault.scroll_fully": "Voll",
        "helpbox.ui.vault.enable_vault": "Tresor-Overlay aktivieren",
        "helpbox.ui.vault.enable_rift": "Rift-Tresor aktivieren",
        "helpbox.ui.vault.save_close": "Speichern & Schließen",
        "helpbox.ui.tab.sacks": "HelpBox Säcke",
        "helpbox.ui.sacks.title": "HelpBox Säcke",
        "helpbox.ui.sacks.subtitle": "Hypixel SkyBlock Sack-Verwaltung & Schnellzugriff",
        "helpbox.ui.buttons.rp_on": "🎨 Ressourcenpaket: AN",
        "helpbox.ui.buttons.rp_off": "🎨 Ressourcenpaket: AUS",
        "helpbox.ui.picker.title": "✦ Symbol- & Blockauswahl",
        "helpbox.ui.picker.search_hint": "Symbole oder Gegenstände suchen...",
        "helpbox.ui.picker.choose": "Symbol wählen",
        "helpbox.ui.picker.open_hint": "Klicken zum Öffnen der Symbolauswahl",
        "helpbox.ui.picker.selected": "✓ Symbol ausgewählt: %s",
        "helpbox.ui.picker.rp_on": "🎨 Ressourcenpaket: AN",
        "helpbox.ui.picker.rp_off": "🎨 Ressourcenpaket: AUS"
    },
    "es_es": {
        "helpbox.ui.sacks.first_time_title": "Aún no hay datos de sacos guardados",
        "helpbox.ui.sacks.first_time_desc": "Por favor, cierre y vuelva a abrir la pantalla para cargar los datos.",
        "helpbox.ui.sacks.btn_fetch": "🔄 Obtener datos de sacos",
        "helpbox.ui.tab.storage": "Bóveda HelpBox",
        "helpbox.ui.storage.title": "Bóveda HelpBox",
        "helpbox.ui.storage.subtitle": "Superposiciones unificadas para Cofres de Ender, Mochilas y Rift",
        "helpbox.ui.vault.title": "Bóveda HelpBox",
        "helpbox.ui.vault.settings": "Ajustes de Bóveda",
        "helpbox.ui.vault.settings_btn": "✦ Abrir ajustes de bóveda",
        "helpbox.ui.vault.settings_title": "✦ Ajustes de Bóveda HelpBox",
        "helpbox.ui.vault.theme": "Tema visual:",
        "helpbox.ui.vault.pages_per_row": "Tarjetas por fila:",
        "helpbox.ui.vault.card_spacing": "Espaciado (px):",
        "helpbox.ui.vault.auto_scroll": "Auto-desplazamiento:",
        "helpbox.ui.vault.scroll_off": "Desactivado",
        "helpbox.ui.vault.scroll_partly": "Parcial",
        "helpbox.ui.vault.scroll_fully": "Completo",
        "helpbox.ui.vault.enable_vault": "Activar interfaz de bóveda",
        "helpbox.ui.vault.enable_rift": "Activar bóveda de Rift",
        "helpbox.ui.vault.save_close": "Guardar y cerrar",
        "helpbox.ui.tab.sacks": "Sacos HelpBox",
        "helpbox.ui.sacks.title": "Sacos HelpBox",
        "helpbox.ui.sacks.subtitle": "Gestión de sacos y acceso rápido de Hypixel SkyBlock",
        "helpbox.ui.buttons.rp_on": "🎨 Paquete de recursos: ACTIVADO",
        "helpbox.ui.buttons.rp_off": "🎨 Paquete de recursos: DESACTIVADO",
        "helpbox.ui.picker.title": "✦ Selector de iconos y bloques",
        "helpbox.ui.picker.search_hint": "Buscar iconos u objetos...",
        "helpbox.ui.picker.choose": "Elegir icono",
        "helpbox.ui.picker.open_hint": "Haga clic para abrir el selector",
        "helpbox.ui.picker.selected": "✓ Icono seleccionado: %s",
        "helpbox.ui.picker.rp_on": "🎨 Paquete de recursos: ACTIVADO",
        "helpbox.ui.picker.rp_off": "🎨 Paquete de recursos: DESACTIVADO"
    },
    "fr_fr": {
        "helpbox.ui.sacks.first_time_title": "Aucune donnée de sacs en cache",
        "helpbox.ui.sacks.first_time_desc": "Veuillez fermer et rouvrir l'écran pour charger les données.",
        "helpbox.ui.sacks.btn_fetch": "🔄 Charger les données de sacs",
        "helpbox.ui.tab.storage": "Coffre-fort HelpBox",
        "helpbox.ui.storage.title": "Coffre-fort HelpBox",
        "helpbox.ui.storage.subtitle": "Interface unifiée pour Coffres de l'Ender, Sacs à dos et Rift",
        "helpbox.ui.vault.title": "Coffre-fort HelpBox",
        "helpbox.ui.vault.settings": "Paramètres du coffre",
        "helpbox.ui.vault.settings_btn": "✦ Ouvrir les paramètres",
        "helpbox.ui.vault.settings_title": "✦ Paramètres du Coffre-fort HelpBox",
        "helpbox.ui.vault.theme": "Thème visuel :",
        "helpbox.ui.vault.pages_per_row": "Cartes par ligne :",
        "helpbox.ui.vault.card_spacing": "Espacement (px) :",
        "helpbox.ui.vault.auto_scroll": "Défilement auto :",
        "helpbox.ui.vault.scroll_off": "Désactivé",
        "helpbox.ui.vault.scroll_partly": "Partiel",
        "helpbox.ui.vault.scroll_fully": "Total",
        "helpbox.ui.vault.enable_vault": "Activer le coffre-fort",
        "helpbox.ui.vault.enable_rift": "Activer le coffre Rift",
        "helpbox.ui.vault.save_close": "Enregistrer & Fermer",
        "helpbox.ui.tab.sacks": "Sacs HelpBox",
        "helpbox.ui.sacks.title": "Sacs HelpBox",
        "helpbox.ui.sacks.subtitle": "Gestion des sacs et accès rapide Hypixel SkyBlock",
        "helpbox.ui.buttons.rp_on": "🎨 Pack de ressources : ACTIF",
        "helpbox.ui.buttons.rp_off": "🎨 Pack de ressources : INACTIF",
        "helpbox.ui.picker.title": "✦ Sélecteur d'icônes et blocs",
        "helpbox.ui.picker.search_hint": "Rechercher des icônes...",
        "helpbox.ui.picker.choose": "Choisir",
        "helpbox.ui.picker.open_hint": "Cliquer pour ouvrir le sélecteur",
        "helpbox.ui.picker.selected": "✓ Icône sélectionnée : %s",
        "helpbox.ui.picker.rp_on": "🎨 Pack de ressources : ACTIF",
        "helpbox.ui.picker.rp_off": "🎨 Pack de ressources : INACTIF"
    },
    "pt_br": {
        "helpbox.ui.sacks.first_time_title": "Nenhum dado de sacos em cache",
        "helpbox.ui.sacks.first_time_desc": "Feche e abra a tela novamente para carregar os dados.",
        "helpbox.ui.sacks.btn_fetch": "🔄 Carregar dados de sacos",
        "helpbox.ui.tab.storage": "Cofre HelpBox",
        "helpbox.ui.storage.title": "Cofre HelpBox",
        "helpbox.ui.storage.subtitle": "Interface unificada para Baús do Ender, Mochilas e Rift",
        "helpbox.ui.vault.title": "Cofre HelpBox",
        "helpbox.ui.vault.settings": "Configurações do Cofre",
        "helpbox.ui.vault.settings_btn": "✦ Abrir configurações do cofre",
        "helpbox.ui.vault.settings_title": "✦ Configurações do Cofre HelpBox",
        "helpbox.ui.vault.theme": "Tema visual:",
        "helpbox.ui.vault.pages_per_row": "Cartões por linha:",
        "helpbox.ui.vault.card_spacing": "Espaçamento (px):",
        "helpbox.ui.vault.auto_scroll": "Rolagem automática:",
        "helpbox.ui.vault.scroll_off": "Desativado",
        "helpbox.ui.vault.scroll_partly": "Parcial",
        "helpbox.ui.vault.scroll_fully": "Total",
        "helpbox.ui.vault.enable_vault": "Ativar interface de cofre",
        "helpbox.ui.vault.enable_rift": "Ativar cofre do Rift",
        "helpbox.ui.vault.save_close": "Salvar e Fechar",
        "helpbox.ui.tab.sacks": "Sacos HelpBox",
        "helpbox.ui.sacks.title": "Sacos HelpBox",
        "helpbox.ui.sacks.subtitle": "Gerenciamento de sacos e acesso rápido Hypixel SkyBlock",
        "helpbox.ui.buttons.rp_on": "🎨 Pacote de Recursos: ATIVADO",
        "helpbox.ui.buttons.rp_off": "🎨 Pacote de Recursos: DESATIVADO",
        "helpbox.ui.picker.title": "✦ Seletor de Ícones e Blocos",
        "helpbox.ui.picker.search_hint": "Buscar ícones ou itens...",
        "helpbox.ui.picker.choose": "Escolher",
        "helpbox.ui.picker.open_hint": "Clique para abrir o seletor",
        "helpbox.ui.picker.selected": "✓ Ícone selecionado: %s",
        "helpbox.ui.picker.rp_on": "🎨 Pacote de Recursos: ATIVADO",
        "helpbox.ui.picker.rp_off": "🎨 Pacote de Recursos: DESATIVADO"
    },
    "ru_ru": {
        "helpbox.ui.sacks.first_time_title": "Данные мешков ещё не загружены",
        "helpbox.ui.sacks.first_time_desc": "Пожалуйста, закройте и снова откройте экран для загрузки данных.",
        "helpbox.ui.sacks.btn_fetch": "🔄 Загрузить данные мешков",
        "helpbox.ui.tab.storage": "Хранилище HelpBox",
        "helpbox.ui.storage.title": "Хранилище HelpBox",
        "helpbox.ui.storage.subtitle": "Удобный интерфейс для сундуков Эндера, рюкзаков и Rift",
        "helpbox.ui.vault.title": "Хранилище HelpBox",
        "helpbox.ui.vault.settings": "Настройки хранилища",
        "helpbox.ui.vault.settings_btn": "✦ Открыть настройки хранилища",
        "helpbox.ui.vault.settings_title": "✦ Настройки хранилища HelpBox",
        "helpbox.ui.vault.theme": "Тема оформления:",
        "helpbox.ui.vault.pages_per_row": "Карточек в строке:",
        "helpbox.ui.vault.card_spacing": "Отступ карточек (px):",
        "helpbox.ui.vault.auto_scroll": "Автопрокрутка:",
        "helpbox.ui.vault.scroll_off": "Выкл",
        "helpbox.ui.vault.scroll_partly": "Частично",
        "helpbox.ui.vault.scroll_fully": "Полностью",
        "helpbox.ui.vault.enable_vault": "Включить хранилище",
        "helpbox.ui.vault.enable_rift": "Включить хранилище Rift",
        "helpbox.ui.vault.save_close": "Сохранить и закрыть",
        "helpbox.ui.tab.sacks": "Мешки HelpBox",
        "helpbox.ui.sacks.title": "Мешки HelpBox",
        "helpbox.ui.sacks.subtitle": "Управление мешками и быстрый доступ Hypixel SkyBlock",
        "helpbox.ui.buttons.rp_on": "🎨 Ресурспак: ВКЛ",
        "helpbox.ui.buttons.rp_off": "🎨 Ресурспак: ВЫКЛ",
        "helpbox.ui.picker.title": "✦ Выбор иконок и блоков",
        "helpbox.ui.picker.search_hint": "Поиск иконок и предметов...",
        "helpbox.ui.picker.choose": "Выбрать",
        "helpbox.ui.picker.open_hint": "Нажмите для выбора иконки",
        "helpbox.ui.picker.selected": "✓ Выбрана иконка: %s",
        "helpbox.ui.picker.rp_on": "🎨 Ресурспак: ВКЛ",
        "helpbox.ui.picker.rp_off": "🎨 Ресурспак: ВЫКЛ"
    },
    "zh_cn": {
        "helpbox.ui.sacks.first_time_title": "尚未缓存袋子数据",
        "helpbox.ui.sacks.first_time_desc": "请关闭并重新打开一次界面以同步数据。",
        "helpbox.ui.sacks.btn_fetch": "🔄 获取袋子数据",
        "helpbox.ui.tab.storage": "HelpBox 保险库",
        "helpbox.ui.storage.title": "HelpBox 保险库",
        "helpbox.ui.storage.subtitle": "末影箱、背包及裂隙的现代化整合存储覆盖层",
        "helpbox.ui.vault.title": "HelpBox 保险库",
        "helpbox.ui.vault.settings": "保险库设置",
        "helpbox.ui.vault.settings_btn": "✦ 打开保险库设置",
        "helpbox.ui.vault.settings_title": "✦ HelpBox 保险库设置",
        "helpbox.ui.vault.theme": "外观主题：",
        "helpbox.ui.vault.pages_per_row": "每行卡片数：",
        "helpbox.ui.vault.card_spacing": "卡片间距 (px)：",
        "helpbox.ui.vault.auto_scroll": "自动滚动：",
        "helpbox.ui.vault.scroll_off": "关闭",
        "helpbox.ui.vault.scroll_partly": "部分",
        "helpbox.ui.vault.scroll_fully": "完全",
        "helpbox.ui.vault.enable_vault": "启用保险库界面",
        "helpbox.ui.vault.enable_rift": "启用裂隙保险库",
        "helpbox.ui.vault.save_close": "保存并关闭",
        "helpbox.ui.tab.sacks": "HelpBox 袋子",
        "helpbox.ui.sacks.title": "HelpBox 袋子",
        "helpbox.ui.sacks.subtitle": "Hypixel SkyBlock 袋子管理与快速访问",
        "helpbox.ui.buttons.rp_on": "🎨 材质包：开启",
        "helpbox.ui.buttons.rp_off": "🎨 材质包：关闭",
        "helpbox.ui.picker.title": "✦ 图标与方块选择器",
        "helpbox.ui.picker.search_hint": "搜索图标或物品...",
        "helpbox.ui.picker.choose": "选择图标",
        "helpbox.ui.picker.open_hint": "点击打开图标选择器",
        "helpbox.ui.picker.selected": "✓ 已选图标：%s",
        "helpbox.ui.picker.rp_on": "🎨 材质包：开启",
        "helpbox.ui.picker.rp_off": "🎨 材质包：关闭"
    },
    "ja_jp": {
        "helpbox.ui.sacks.first_time_title": "サックデータがまだありません",
        "helpbox.ui.sacks.first_time_desc": "データを読み込むには、画面を一度閉じて再度開いてください。",
        "helpbox.ui.sacks.btn_fetch": "🔄 サックデータを取得",
        "helpbox.ui.tab.storage": "HelpBox 金庫",
        "helpbox.ui.storage.title": "HelpBox 金庫",
        "helpbox.ui.storage.subtitle": "エンダーチェスト、バックパック、リフト用オーバーレイ",
        "helpbox.ui.vault.title": "HelpBox 金庫",
        "helpbox.ui.vault.settings": "金庫の設定",
        "helpbox.ui.vault.settings_btn": "✦ 金庫設定を開く",
        "helpbox.ui.vault.settings_title": "✦ HelpBox 金庫設定",
        "helpbox.ui.vault.theme": "表示テーマ:",
        "helpbox.ui.vault.pages_per_row": "1行あたりのカード数:",
        "helpbox.ui.vault.card_spacing": "カード間隔 (px):",
        "helpbox.ui.vault.auto_scroll": "自動スクロール:",
        "helpbox.ui.vault.scroll_off": "オフ",
        "helpbox.ui.vault.scroll_partly": "一部",
        "helpbox.ui.vault.scroll_fully": "完全",
        "helpbox.ui.vault.enable_vault": "金庫オーバーレイを有効化",
        "helpbox.ui.vault.enable_rift": "リフト金庫を有効化",
        "helpbox.ui.vault.save_close": "保存して閉じる",
        "helpbox.ui.tab.sacks": "HelpBox サック",
        "helpbox.ui.sacks.title": "HelpBox サック",
        "helpbox.ui.sacks.subtitle": "Hypixel SkyBlock サック管理とクイックアクセス",
        "helpbox.ui.buttons.rp_on": "🎨 リソースパック: オン",
        "helpbox.ui.buttons.rp_off": "🎨 リソースパック: オフ",
        "helpbox.ui.picker.title": "✦ アイコン＆ブロックピッカー",
        "helpbox.ui.picker.search_hint": "アイコンまたはアイテムを検索...",
        "helpbox.ui.picker.choose": "アイコン選択",
        "helpbox.ui.picker.open_hint": "クリックして選択画面を開く",
        "helpbox.ui.picker.selected": "✓ アイコンを選択しました: %s",
        "helpbox.ui.picker.rp_on": "🎨 リソースパック: オン",
        "helpbox.ui.picker.rp_off": "🎨 リソースパック: オフ"
    },
    "ar_sa": {
        "helpbox.ui.sacks.first_time_title": "لم يتم تخزين بيانات الأكياس بعد",
        "helpbox.ui.sacks.first_time_desc": "يرجى إغلاق الشاشة وإعادة فتحها مرة واحدة لتحميل البيانات.",
        "helpbox.ui.sacks.btn_fetch": "🔄 جلب بيانات الأكياس",
        "helpbox.ui.tab.storage": "خزينة HelpBox",
        "helpbox.ui.storage.title": "خزينة HelpBox",
        "helpbox.ui.storage.subtitle": "واجهة موحدة لصناديق الإندر وحقائب الظهر والريفت",
        "helpbox.ui.vault.title": "خزينة HelpBox",
        "helpbox.ui.vault.settings": "إعدادات الخزينة",
        "helpbox.ui.vault.settings_btn": "✦ فتح إعدادات الخزينة",
        "helpbox.ui.vault.settings_title": "✦ إعدادات خزينة HelpBox",
        "helpbox.ui.vault.theme": "المظهر:",
        "helpbox.ui.vault.pages_per_row": "البطاقات في كل صف:",
        "helpbox.ui.vault.card_spacing": "تباعد البطاقات (px):",
        "helpbox.ui.vault.auto_scroll": "التمرير التلقائي:",
        "helpbox.ui.vault.scroll_off": "معطل",
        "helpbox.ui.vault.scroll_partly": "جزئي",
        "helpbox.ui.vault.scroll_fully": "كامل",
        "helpbox.ui.vault.enable_vault": "تفعيل واجهة الخزينة",
        "helpbox.ui.vault.enable_rift": "تفعيل خزينة الريفت",
        "helpbox.ui.vault.save_close": "حفظ وإغلاق",
        "helpbox.ui.tab.sacks": "أكياس HelpBox",
        "helpbox.ui.sacks.title": "أكياس HelpBox",
        "helpbox.ui.sacks.subtitle": "إدارة أكياس Hypixel SkyBlock والوصول السريع",
        "helpbox.ui.buttons.rp_on": "🎨 حزمة الموارد: مفعّل",
        "helpbox.ui.buttons.rp_off": "🎨 حزمة الموارد: معطّل",
        "helpbox.ui.picker.title": "✦ منتقي الأيقونات والكتل",
        "helpbox.ui.picker.search_hint": "ابحث عن أيقونات أو عناصر...",
        "helpbox.ui.picker.choose": "اختر أيقونة",
        "helpbox.ui.picker.open_hint": "انقر لفتح منتقي الأيقونات",
        "helpbox.ui.picker.selected": "✓ تم اختيار الأيقونة: %s",
        "helpbox.ui.picker.rp_on": "🎨 حزمة الموارد: مفعّل",
        "helpbox.ui.picker.rp_off": "🎨 حزمة الموارد: معطّل"
    },
    "hi_in": {
        "helpbox.ui.sacks.first_time_title": "अभी तक कोई बोरी डेटा संग्रहीत नहीं है",
        "helpbox.ui.sacks.first_time_desc": "डेटा लोड करने के लिए कृपया स्क्रीन को एक बार बंद करके फिर से खोलें।",
        "helpbox.ui.sacks.btn_fetch": "🔄 बोरी डेटा लाएं",
        "helpbox.ui.tab.storage": "HelpBox तिजोरी",
        "helpbox.ui.storage.title": "HelpBox तिजोरी",
        "helpbox.ui.storage.subtitle": "एंडर चेस्ट, बैकपैक्स और रिफ्ट के लिए आधुनिक ओवरले",
        "helpbox.ui.vault.title": "HelpBox तिजोरी",
        "helpbox.ui.vault.settings": "तिजोरी सेटिंग्स",
        "helpbox.ui.vault.settings_btn": "✦ तिजोरी सेटिंग्स खोलें",
        "helpbox.ui.vault.settings_title": "✦ HelpBox तिजोरी सेटिंग्स",
        "helpbox.ui.vault.theme": "थीम:",
        "helpbox.ui.vault.pages_per_row": "प्रति पंक्ति कार्ड:",
        "helpbox.ui.vault.card_spacing": "कार्ड रिक्ति (px):",
        "helpbox.ui.vault.auto_scroll": "ऑटो-स्क्रॉल:",
        "helpbox.ui.vault.scroll_off": "बंद",
        "helpbox.ui.vault.scroll_partly": "आंशिक",
        "helpbox.ui.vault.scroll_fully": "पूर्ण",
        "helpbox.ui.vault.enable_vault": "तिजोरी ओवरले सक्षम करें",
        "helpbox.ui.vault.enable_rift": "रिफ्ट तिजोरी सक्षम करें",
        "helpbox.ui.vault.save_close": "सहेजें और बंद करें",
        "helpbox.ui.tab.sacks": "HelpBox बोरियां",
        "helpbox.ui.sacks.title": "HelpBox बोरियां",
        "helpbox.ui.sacks.subtitle": "Hypixel SkyBlock बोरी प्रबंधन और त्वरित पहुंच",
        "helpbox.ui.buttons.rp_on": "🎨 रिसोर्स पैक: चालू",
        "helpbox.ui.buttons.rp_off": "🎨 रिसोर्स पैक: बंद",
        "helpbox.ui.picker.title": "✦ आइकन और ब्लॉक पिकर",
        "helpbox.ui.picker.search_hint": "आइकन या आइटम खोजें...",
        "helpbox.ui.picker.choose": "आइकन चुनें",
        "helpbox.ui.picker.open_hint": "आइकन पिकर खोलने के लिए क्लिक करें",
        "helpbox.ui.picker.selected": "✓ चयनित आइकन: %s",
        "helpbox.ui.picker.rp_on": "🎨 रिसोर्स पैक: चालू",
        "helpbox.ui.picker.rp_off": "🎨 रिसोर्स पैक: बंद"
    }
}

MODULES = ["26.3", "26.2", "26.1.2"]

for mod in MODULES:
    lang_dir = os.path.join(mod, "src", "main", "resources", "assets", "helpbox", "lang")
    if not os.path.isdir(lang_dir):
        print(f"Directory {lang_dir} does not exist, skipping.")
        continue

    for lang_code, trans in TRANSLATIONS.items():
        file_path = os.path.join(lang_dir, f"{lang_code}.json")
        data = {}
        if os.path.exists(file_path):
            with open(file_path, "r", encoding="utf-8") as f:
                try:
                    data = json.load(f)
                except Exception as e:
                    print(f"Error loading {file_path}: {e}")
                    data = {}

        # Update keys
        for k, v in trans.items():
            data[k] = v

        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")
        print(f"Updated {file_path}")

print("All language files successfully updated!")
